# Submission Guidelines:

*   Make a copy of the file in your drive and rename the file with your id_section. e.g. **190204001_A1**
* You will have **20 minutes** to finish the task
* If you finish within the time **raise your hand**
* Everyone must make the final submission of the .ipynb file in the following google form: https://forms.gle/qaDrBb61YwqQumgi6
* **Any form of copying, plagiarism, or unauthorized collaboration is strictly prohibited and your exam will be cancelled if you are found guilty**

#Online 1
We need to complete the templete code to solve a 3 class classification problem. You nedd to complete the following tasks:

1.   Step #1: **data** tensor contains the input features and the **label** tensor contains the outputs. You need to apply slicing to extract the first and last features and assign the **first 40 data** to x_data and outputs to y_data.<br>
Additionally define the hyperparameters with **number of epochs having 100 + (last 2 digits of your id) and learning rate is 0.01**
2.   Step #2: Design the models with following layers:<br>**Input Layer -> Linear Layer -> ReLU -> Linear Layer -> Sigmoid -> Output Layer**
3. Step #3: Define the loss function as **Cross Entropy Loss** and Optimizer as **Stochastic Gradient Descent (SGD)**
4. Step #4: Complete the **forwad pass and loss calculation step** in training loop
5. Step #5: Make prediction on the last 10 samples from the data tensor and print the predicted class<br>

In [8]:
from torch import nn
import torch
from torch import tensor

### Step #1 : Define input, output and hyperparameters

In [11]:
torch.manual_seed(42)

data = torch.rand(50, 4, dtype = torch.float32)
data = data * 100
data = torch.round(data)

label = torch.tensor([2 if x > 70 else 1 if x < 70 and x > 40 else 0 for x in data[:, 0] ], dtype = torch.float32)
print(label)

tensor([2., 0., 2., 2., 2., 0., 0., 1., 2., 1., 1., 2., 2., 0., 1., 1., 1., 0.,
        2., 0., 0., 2., 0., 2., 2., 0., 1., 0., 1., 1., 1., 0., 2., 0., 0., 1.,
        1., 2., 1., 2., 2., 2., 1., 2., 0., 1., 2., 0., 2., 1.])


In [12]:
#Complete the following codes
x_data = data[:40, :2]
y_data = label[:40]

print(x_data)
print(y_data)

# Hyper-parameters
input_size = x_data.shape[1]
output_size = 1
num_epochs = 105
learning_rate = 0.01

tensor([[88., 92.],
        [39., 60.],
        [94., 13.],
        [87., 57.],
        [89., 57.],
        [27., 44.],
        [11., 27.],
        [55.,  1.],
        [89., 58.],
        [58., 90.],
        [63., 36.],
        [79., 28.],
        [75., 20.],
        [12., 91.],
        [66., 49.],
        [53., 16.],
        [65., 40.],
        [20., 20.],
        [98.,  9.],
        [16., 70.],
        [24., 16.],
        [80., 38.],
        [25., 65.],
        [80., 84.],
        [96., 33.],
        [21., 62.],
        [51., 16.],
        [ 6., 18.],
        [65.,  3.],
        [58.,  6.],
        [50., 31.],
        [16., 21.],
        [92., 40.],
        [ 8., 85.],
        [ 8.,  0.],
        [69.,  9.],
        [41., 60.],
        [96., 10.],
        [45., 13.],
        [77., 68.]])
tensor([2., 0., 2., 2., 2., 0., 0., 1., 2., 1., 1., 2., 2., 0., 1., 1., 1., 0.,
        2., 0., 0., 2., 0., 2., 2., 0., 1., 0., 1., 1., 1., 0., 2., 0., 0., 1.,
        1., 2., 1., 2.])


### Step #2 : Design your model using class with Variables

In [13]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        #Complete the following code
        self.linear1 = nn.Linear(input_size, 10)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(10, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        #Complete the following code
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        y_pred = self.sigmoid(x)

        return y_pred


# our model
model = Model()
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

Model(
  (linear1): Linear(in_features=2, out_features=10, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=10, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

###Step #3 : Construct loss and optimizer (select from PyTorch API)

In [17]:
#Complete the following code
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

###Step #4 : Training: forward, loss, backward, step

In [18]:

# Training loop
for epoch in range(num_epochs):

    #Complete the following code
    y_pred = model(x_data.to(device))
    y_pred = y_pred.squeeze()
    loss = criterion(y_pred, y_data.to(device))

    print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



Epoch: 0 | Loss: 148.37445068359375 
Epoch: 1 | Loss: 151.446044921875 
Epoch: 2 | Loss: 151.42813110351562 
Epoch: 3 | Loss: 151.41265869140625 
Epoch: 4 | Loss: 151.39926147460938 
Epoch: 5 | Loss: 151.38755798339844 
Epoch: 6 | Loss: 151.37725830078125 
Epoch: 7 | Loss: 151.36817932128906 
Epoch: 8 | Loss: 151.360107421875 
Epoch: 9 | Loss: 151.3529052734375 
Epoch: 10 | Loss: 151.34646606445312 
Epoch: 11 | Loss: 151.34063720703125 
Epoch: 12 | Loss: 151.33535766601562 
Epoch: 13 | Loss: 151.33058166503906 
Epoch: 14 | Loss: 151.3262481689453 
Epoch: 15 | Loss: 151.32225036621094 
Epoch: 16 | Loss: 151.318603515625 
Epoch: 17 | Loss: 151.31524658203125 
Epoch: 18 | Loss: 151.3121337890625 
Epoch: 19 | Loss: 151.3092803955078 
Epoch: 20 | Loss: 151.3065948486328 
Epoch: 21 | Loss: 151.30413818359375 
Epoch: 22 | Loss: 151.3018035888672 
Epoch: 23 | Loss: 151.29966735839844 
Epoch: 24 | Loss: 151.29766845703125 
Epoch: 25 | Loss: 151.2957763671875 
Epoch: 26 | Loss: 151.2940063476562

###Step #5 : Prediction

In [19]:
# Prediction on unseen data and print the predicted class
test_data = data[-10:, :2]
with torch.no_grad():
    predictions = model(test_data.to(device))
    predicted_classes = (predictions > 0.5).float()

print("\nPredicted Classes for the last 10 samples:")
for i in range(len(test_data)):
    print(f'Test Data: {test_data[i]}, Predicted Class: {predicted_classes[i].item()}')



Predicted Classes for the last 10 samples:
Test Data: tensor([95., 61.]), Predicted Class: 0.0
Test Data: tensor([71., 42.]), Predicted Class: 0.0
Test Data: tensor([61., 22.]), Predicted Class: 0.0
Test Data: tensor([78., 37.]), Predicted Class: 0.0
Test Data: tensor([13., 68.]), Predicted Class: 0.0
Test Data: tensor([62., 76.]), Predicted Class: 0.0
Test Data: tensor([76., 76.]), Predicted Class: 0.0
Test Data: tensor([37., 55.]), Predicted Class: 0.0
Test Data: tensor([82., 93.]), Predicted Class: 0.0
Test Data: tensor([51., 47.]), Predicted Class: 0.0
